name: Build Lambda Layer (Python 3.12)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create layer folder
        run: mkdir -p python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install qrcode[pil] -t python

      - name: Debug folder contents
        run: ls -R python

      - name: Create zip
        run: zip -r qrcode-layer.zip python

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qrcode-layer-python312
          path: qrcode-layer.zip
